name: Run Automated Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v4

    - name: Настройка Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'Lab9/requirements.txt'

    - name: Установка зависимостей
      working-directory: ./Lab9
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск тестов через pytest
      working-directory: ./Lab9
      run: |
        pytest -v